name: bemestaremmaos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if você deseja publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  flutter:
   sdk: flutter
  sqflite: ^2.2.7
  sqflite_common_ffi: ^2.2.7
  path: ^1.8.3

  # Pacote de calendário que você está usando
  table_calendar: ^3.0.8

  # Pacote para ícones estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Declaração das imagens do projeto
  assets:
    - assets/images/logo.png
    - assets/images/item0.jpg
    - assets/images/item1.jpg
    - assets/images/item2.jpg
    - assets/images/item3.jpg
    - assets/images/item4.jpg 
    - assets/images/item5.jpg
    - assets/images/curvatura.jpg 
    - assets/images/skincare.jpg
    - assets/images/reconstrucao.jpg 
    - assets/images/hidratacao.jpeg
    - assets/images/unhaslixas.jpg 
    - assets/images/hidratacaounhas.jpg
    - assets/images/reconstrucao.jpg 
    - assets/images/formatodeunhas.jpg
    - assets/images/atividadefisica.jpg
    - assets/images/correr.jpg 
    - assets/images/beberagua.jpg
    - assets/images/pele.jpg 
    - assets/images/hidratacaopele.jpg
    - assets/images/colica.jpg
    - assets/images/fases.jpg 
    - assets/images/hormoniosdociclo.jpg
    - assets/images/avatar.jpg
    - assets/images/1.png